### ISSUE TITLE
fontsize() funktioniert nicht

### ISSUE THREAD

**Issue by kantel** [karstenw/nodebox-pyobjc#2]
Gebe ich das Programm`Zapfun` aus der Nodebox-Dokumentation so ein, wie im Screenshot <https://www.nodebox.net/code/index.php/Strings>, also

~~~python
   fontsize(random(400))
~~~
 werden alle Buchstaben in der Defaultgröße (vermutlich 12pt) ausgegeben, schreibe ich aber in der Schleife

~~~python
   font("Zapfino", random(400))
~~~

bekomme ich den erwünschten Effekt.  Hier der Screenshot meiner leicht abgeänderten Version, die auch japanisch kann. 😎

![bildschirmfoto 2018-02-04 um 18 24 08](https://user-images.githubusercontent.com/1219909/35780245-d77ef48e-09d8-11e8-8217-f24df92e9e74.png)

**Comment by karstenw** [comment]
On 04.02.2018, at 18:27, Jörg Kantel wrote:

> Gebe ich das ProgrammZapfun aus der Nodebox-Dokumentation so ein, wie im Screenshot https://www.nodebox.net/code/index.php/Strings, also
> 
>    fontsize(random(400))
> werden alle Buchstaben in der Defaultgröße (vermutlich 12pt) ausgegeben, schreibe ich aber in der Schleife
> 
>    font("Zapfino", random(400))
> bekomme ich den erwünschten Effekt. Hier der Screenshot meiner leicht abgeänderten Version, die auch japanisch kann.

Ich habe versucht, das zu rekonstruieren aber bei mir läuft es wie erwartet.

Evtl. hast du einen schlechten random Lauf bekommen. Das ist zwar unwahrscheinlich, kann aber nichtsdestotrotz vorkommen.

Ich benutze dann random(100,200) um eine Mindestgrösse reinzurechnen.


-karsten

**Comment by kantel** [comment]
Was immer es war, Du hast recht – bei mir funzt es jetzt auch.

![bildschirmfoto 2018-02-04 um 18 48 28](https://user-images.githubusercontent.com/1219909/35780464-11122fd8-09dc-11e8-901f-3603af3f033c.png)

Sorry für die Konfusion.
